project:
  type: website
  output-dir: docs

website:
  title: "Rishit Jakharia"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog


format:
  html:
    theme:
      light: [litera, styles-light.scss]
      dark: [darkly, styles-dark.scss]
    highlight-style: 
      light: github
      dark: atom-one-dark
    mainfont: "Roboto"
    code-copy: true
    code-overflow: wrap


execute:
  freeze: auto